# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [ push ]
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_clang_8_cuda_10:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: test
      run: |
        export cache_name=github_${GITHUB_REF##*/}
        export cc_path="clang++-8"
        export cc_flags=" -g "
        export log_sync=0
        export log_v=0
        export PYTHONIOENCODING=utf8
        export PYTHONPATH=`pwd`/python
        export nvcc_path=/usr/local/cuda/bin/nvcc
        python3.7 -c "import jittor"
        python3.7 -m jittor.test -v
        
  test_gcc:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: test
      run: |
        export cache_name=github_${GITHUB_REF##*/}
        export cc_path="g++"
        export cc_flags=" -g "
        export log_sync=0
        export log_v=0
        export PYTHONIOENCODING=utf8
        export PYTHONPATH=`pwd`/python
        export nvcc_path=
        python3.7 -c "import jittor"
        python3.7 -m jittor.test -v